<?php

namespace Carto\DonneesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RSynsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RSynsetRepository extends EntityRepository
{
}
