<?php

namespace Carto\DonneesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VSynsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VSynsetRepository extends EntityRepository
{
}
