imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
#Ancienne URL A REMPLACER dans les lignes ci dessous (Pas de Quot , pas de guillemets)
#URL MAIN ACTION
#var url = "http://localhost/bundles/CartoRepresentationsBundle/action/main_action.php"; // remy
#var url = "http://carto.localhost/bundles/CartoRepresentationsBundle/action/main_action.php"; // Celine
#var url = "http://127.0.0.1/bundles/CartoRepresentationsBundle/action/main_action.php"; // remi
#var url = "http://localhost/CartoSavoie/carto/web/bundles/CartoRepresentationsBundle/action/main_action.php"; // Juliana
#var url = "http://localhost/Projet%20-%20Visualisation%20de%20donnees/carto/web/bundles/CartoRepresentationsBundle/action/main_action.php"; //Anthony
#var url = "http://carto.dev/bundles/CartoRepresentationsBundle/action/main_action.php"; //Anthony2
#URL DONNEE JSON
#return 'http://carto.localhost/fr/donnees/json/'; //Céline 
#return 'http://localhost/CartoSavoie/carto/web/fr/donnees/json/'; //Juliana
#return 'http://localhost/Projet%20-%20Visualisation%20de%20donnees/carto/web/fr/donnees/json/'// Anthony
#return 'http://carto.dev/fr/donnees/json/';// Anthony2
#return 'http://localhost/app_dev.php/en/donnees/json/'; // remy
#URL DONNEE DBPEDIA
#return 'http://carto.localhost/fr/donnees/dbpedia/json/'; //Céline
#return 'http://localhost/CartoSavoie/carto/web/fr/donnees/dbpedia/json/'; //Juliana
#return 'http://localhost/Projet%20-%20Visualisation%20de%20donnees/carto/web/fr/donnees/dbpedia/json/'; // Anthony
#return 'http://carto.dev/fr/donnees/dbpedia/json/'; // Anthony2
#return 'http://localhost/app_dev.php/en/donnees/dbpedia/json/'; // remy
#URL DONNEE RELATIONS
#return 'http://carto.localhost/fr/donnees/relations'; //Céline
#return 'http://localhost/CartoSavoie/carto/web/fr/donnees/relations'; //Juliana
#return 'http://localhost/Projet%20-%20Visualisation%20de%20donnees/carto/web/fr/donnees/relations'; // Anthony
#return 'http://carto.dev/fr/donnees/relations'; // Anthony2
#return 'http://localhost/app_dev.php/fr/donnees/relations'; // remy
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        urlGlob: http://127.0.0.1/bundles/CartoRepresentationsBundle/action/main_action.php
        urlACTWN: http://127.0.0.1/fr/donnees/json/
        urlACTPB: http://127.0.0.1/fr/donnees/dbpedia/json/
        urlOPTON: http://127.0.0.1/fr/donnees/relations
        urlAUTRE: http://demo4.itpassion.info/crawler.php?target=
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [CartoAccueilBundle, CartoDocumentationBundle, CartoRepresentationsBundle, CartoLivreOrBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Système de captcha
gregwar_captcha: ~

#Url pour recherche WN , DB et pour les action PHP
