carto_donnees:
    resource: "@CartoDonneesBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/donnees
    defaults: {_locale: en}
    requirements:
        _locale: en|fr

carto_representations:
    resource: "@CartoRepresentationsBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/representations
    defaults: {_locale: en}
    requirements:
        _locale: en|fr

carto_documentation:
    resource: "@CartoDocumentationBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/documentation
    defaults: {_locale: en}
    requirements:
        _locale: en|fr

carto_accueil:
    resource: "@CartoAccueilBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    defaults: {_locale: en}
    requirements:
        _locale: en|fr

carto_language:
    resource: "@CartoAccueilBundle/Resources/config/routing.yml"
    prefix:    /{_locale}
    defaults: {_locale: en}
    requirements:
        _locale: en|fr
