security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_admin_login:
            # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern:   /login$
            anonymous: true
            
        main_admin:
            pattern:   /admin
            anonymous: false
            provider:  in_memory
            form_login:
                login_path: carto_donnees_admin_login
                check_path: carto_donnees_admin_login_check
                always_use_default_target_path: true
                default_target_path: /en/donnees/admin
            logout:
                path:   carto_donnees_admin_logout
                target: /

        main:
            pattern:   /
            anonymous: true

    access_control:
        - { path: /admin$, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
