# Admin

carto_donnees_admin_dashboard:
    pattern:  /admin
    defaults: { _controller: CartoDonneesBundle:Dashboard:index }

carto_donnees_admin_login:
    pattern:  /admin/login
    defaults:  { _controller: CartoUserBundle:Security:login }

carto_donnees_admin_login_check:
    pattern:  /admin/login_check

carto_donnees_admin_logout:
    pattern:  /admin/logout

carto_donnees_admin_enregistre:
    pattern:  /admin/enregistrer
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:index }

carto_donnees_admin_sauvegarder:
    pattern:  /admin/sauvegarder/{nom}/{type}/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:sauvegarde }

carto_donnees_admin_sauvegardermots:
    pattern:  /admin/sauvegardermots/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:sauvegardemot }

carto_donnees_admin_derive:
    pattern:  /admin/derive/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:derive }

carto_donnees_admin_builtfrom:
    pattern:  /admin/builtfrom/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:builtfrom }

carto_donnees_admin_participle:
    pattern:  /admin/participle
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:participle }

carto_donnees_admin_pertainym:
    pattern:  /admin/pertainym/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:pertainym }

carto_donnees_admin_antonyms:
    pattern:  /admin/antonyms/{nom}/{type}/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:antonyms }

carto_donnees_admin_hypernyms:
    pattern:  /admin/hypernyms/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:hypernyms }

carto_donnees_admin_meronyms:
    pattern:  /admin/meronyms/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:meronyms }

carto_donnees_admin_attributes:
    pattern:  /admin/attributes/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:attributes }

carto_donnees_admin_troponyms:
    pattern:  /admin/troponyms
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:troponyms }

carto_donnees_admin_entails:
    pattern:  /admin/entails
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:entails }

carto_donnees_admin_causes:
    pattern:  /admin/causes
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:causes }

carto_donnees_admin_similars:
    pattern:  /admin/similars
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:similars }

carto_donnees_admin_recherche:
    pattern:  /admin/recherche/{recherche}
    defaults: { _controller: CartoDonneesBundle:WN:index, recherche:'entity' }

#Client 
carto_donnees_relations:
    pattern: /relations
    defaults: { _controller: CartoDonneesBundle:WN:relations }

carto_donnees_json:
    pattern:  /json/{recherche}/{relations}
    defaults: { _controller: CartoDonneesBundle:WN:json, recherche:'entity', relations:'' }

carto_donnees_simple:
    pattern:  /simple/{recherche}
    defaults: { _controller: CartoDonneesBundle:WN:index, recherche:'entity' }

carto_donnees_dbpedia_json:
    pattern:  /dbpedia/json/{recherche}
    defaults: { _controller: CartoDonneesBundle:DbPedia:index, recherche:'horse' }

