# Admin

carto_donnees_admin_dashboard:
    pattern:  /admin
    defaults: { _controller: CartoDonneesBundle:Dashboard:index }

carto_donnees_admin_login:
    pattern:  /admin/login
    defaults:  { _controller: CartoUserBundle:Security:login }

carto_donnees_admin_login_check:
    pattern:  /admin/login_check

carto_donnees_admin_logout:
    pattern:  /admin/logout

carto_donnees_admin_homepage:
    pattern:  /admin/recherche/{recherche}
    defaults: { _controller: CartoDonneesBundle:Default:index, recherche:'entity' }

carto_donnees_admin_enregistre:
    pattern:  /admin/enregistrer
    defaults: { _controller: CartoDonneesBundle:Enregistre:index }

carto_donnees_admin_sauvegarder:
    pattern:  /admin/sauvegarder/{nom}/{type}/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:Enregistre:sauvegarde }

carto_donnees_admin_sauvegardermots:
    pattern:  /admin/sauvegardermots/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:Enregistre:sauvegardemot }

carto_donnees_admin_derive:
    pattern:  /admin/derive/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:Enregistre:derive }

carto_donnees_admin_builtfrom:
    pattern:  /admin/builtfrom/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:Enregistre:builtfrom }

carto_donnees_admin_participle:
    pattern:  /admin/participle
    defaults: { _controller: CartoDonneesBundle:Enregistre:participle }

carto_donnees_admin_pertainym:
    pattern:  /admin/pertainym/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:Enregistre:pertainym }

carto_donnees_admin_antonyms:
    pattern:  /admin/antonyms/{nom}/{type}/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:Enregistre:antonyms }

carto_donnees_admin_hypernyms:
    pattern:  /admin/hypernyms/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:Enregistre:hypernyms }

carto_donnees_admin_meronyms:
    pattern:  /admin/meronyms/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:Enregistre:meronyms }

carto_donnees_admin_attributes:
    pattern:  /admin/attributes/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:Enregistre:attributes }

carto_donnees_admin_troponyms:
    pattern:  /admin/troponyms
    defaults: { _controller: CartoDonneesBundle:Enregistre:troponyms }

carto_donnees_admin_entails:
    pattern:  /admin/entails
    defaults: { _controller: CartoDonneesBundle:Enregistre:entails }

carto_donnees_admin_causes:
    pattern:  /admin/causes
    defaults: { _controller: CartoDonneesBundle:Enregistre:causes }

carto_donnees_admin_similars:
    pattern:  /admin/similars
    defaults: { _controller: CartoDonneesBundle:Enregistre:similars }

carto_donnees_admin_recherche:
    pattern:  /admin/recherche/{recherche}
    defaults: { _controller: CartoDonneesBundle:Default:index, recherche:'entity' }

#Client 
carto_donnees_json:
    pattern:  /json/{recherche}
    defaults: { _controller: CartoDonneesBundle:Default:json, recherche:'entity' }

