# Admin

carto_donnees_admin_enregistre:
    pattern:  /admin/enregistrer
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:index }

carto_donnees_admin_sauvegarder:
    pattern:  /admin/sauvegarder/{nom}/{type}/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:sauvegarde }

carto_donnees_admin_sauvegardermots:
    pattern:  /admin/sauvegardermots/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:sauvegardemot }

carto_donnees_admin_derive:
    pattern:  /admin/derive/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:derive }

carto_donnees_admin_builtfrom:
    pattern:  /admin/builtfrom/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:builtfrom }

carto_donnees_admin_participle:
    pattern:  /admin/participle
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:participle }

carto_donnees_admin_pertainym:
    pattern:  /admin/pertainym/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:pertainym }

carto_donnees_admin_antonyms:
    pattern:  /admin/antonyms/{nom}/{type}/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:antonyms }

carto_donnees_admin_hypernyms:
    pattern:  /admin/hypernyms/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:hypernyms }

carto_donnees_admin_meronyms:
    pattern:  /admin/meronyms/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:meronyms }

carto_donnees_admin_attributes:
    pattern:  /admin/attributes/{liminf}/{limsup}
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:attributes }

carto_donnees_admin_troponyms:
    pattern:  /admin/troponyms
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:troponyms }

carto_donnees_admin_entails:
    pattern:  /admin/entails
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:entails }

carto_donnees_admin_causes:
    pattern:  /admin/causes
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:causes }

carto_donnees_admin_similars:
    pattern:  /admin/similars
    defaults: { _controller: CartoDonneesBundle:EnregistreWN:similars }

carto_donnees_admin_recherche:
    pattern:  /admin/recherche/{recherche}
    defaults: { _controller: CartoDonneesBundle:WN:index, recherche:'entity' }

carto_donnees_admin_humour_objets:
    pattern:  /admin/humour/objets
    defaults: { _controller: CartoDonneesBundle:Humour:objet }

carto_donnees_admin_humour_objets_supprimer:
    pattern:  /admin/humour/objets/supprimer/{id}
    defaults: { _controller: CartoDonneesBundle:Humour:objetSuppr }

carto_donnees_admin_humour_objets_editer:
    pattern:  /admin/humour/objets/editer/{id}
    defaults: { _controller: CartoDonneesBundle:Humour:objetEdit }

carto_donnees_admin_humour_relations:
    pattern:  /admin/humour/relations
    defaults: { _controller: CartoDonneesBundle:Humour:relation }

carto_donnees_admin_humour_relations_supprimer:
    pattern:  /admin/humour/relations/supprimer/{id}
    defaults: { _controller: CartoDonneesBundle:Humour:relationSuppr }

carto_donnees_admin_humour_triplets:
    pattern:  /admin/humour/triplets
    defaults: { _controller: CartoDonneesBundle:Humour:triplet }

carto_donnees_admin_humour_triplets_supprimer:
    pattern:  /admin/humour/triplets/supprimer/{id}
    defaults: { _controller: CartoDonneesBundle:Humour:tripletSuppr }

#Client 
carto_donnees_relations:
    pattern: /relations
    defaults: { _controller: CartoDonneesBundle:WN:relations }

carto_donnees_json:
    pattern:  /json/{recherche}/{relations}/{profondeur}
    defaults: { _controller: CartoDonneesBundle:WN:json, recherche:'entity', relations:'all', profondeur:3 }

carto_donnees_simple:
    pattern:  /simple/{recherche}
    defaults: { _controller: CartoDonneesBundle:WN:index, recherche:'entity' }

carto_donnees_dbpedia_json:
    pattern:  /dbpedia/json/{recherche}/{limite}
    defaults: { _controller: CartoDonneesBundle:DbPedia:index, recherche:'horse', limite:20 }

carto_donnees_humour_json:
    pattern:  /humour/json/{recherche}/{relations}
    defaults: { _controller: CartoDonneesBundle:Humour:json, recherche:'WordNet', relations:'all' }

carto_donnees_humour_recuprelations:
    pattern: /humour/recuprelations
    defaults: { _controller: CartoDonneesBundle:Humour:recupRelations }

carto_donnees_humour_recupdescription:
    pattern: /humour/description/{mot}
    defaults: { _controller: CartoDonneesBundle:Humour:description }

