parameters:
#    carto_user.example.class: Carto\UserBundle\Example

services:
#    carto_user.example:
#        class: %carto_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
