carto_documentation_homepage:
    pattern:  /
    defaults: { _controller: CartoDocumentationBundle:Default:index }

carto_documentation_projet:
    pattern:  /projet
    defaults: { _controller: CartoDocumentationBundle:Projet:index }
