carto_documentation_homepage:
    pattern:  /
    defaults: { _controller: CartoDocumentationBundle:Default:index }

carto_documentation_projet:
    pattern:  /projet
    defaults: { _controller: CartoDocumentationBundle:Projet:index }

carto_documentation_etudewn:
    pattern:  /WordNet
    defaults: { _controller: CartoDocumentationBundle:EtudeWN:index }

carto_documentation_etudewn_words:
    pattern:  /WordNet/words
    defaults: { _controller: CartoDocumentationBundle:EtudeWN:words }
