parameters:
#    representation.example.class: Carto\RepresentationBundle\Example

services:
#    representation.example:
#        class: %representation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
