<?php

namespace Carto\DonneesBundle\Entity\WN;

use Doctrine\ORM\EntityRepository;

/**
 * MotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotRepository extends EntityRepository
{
	//A enlever, présente juste pour l'apprentissage des tests
	/**
	 * fonction trouve
	 *
	 * @param string $recherche
	 * @return string
	 * @todo : enlever cette fonction et son test à la fin du projet
	*/
	public function trouve($recherche)
	{
		$mot = $this -> findOneByMot($recherche);
		if ($mot != NULL)
		{
			return 'trouve';
		}
		else
		{
			return 'non trouve';
		}
	}
}
