parameters:
#    carto_representations.example.class: Carto\RepresentationsBundle\Example

services:
#    carto_representations.example:
#        class: %carto_representations.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
