parameters:
#    carto_representations.example.class: Carto\RepresentationsBundle\Example

services:
#    carto_representations.obtenirjsonwn:
#        class: Carto\DonneesBundle\Controller\DefaultController
#        arguments: [@service_id, "plain_value", %parameter%]
#    carto_representations.example:
#        class: %carto_representations.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
