<?php

namespace Carto\DonneesBundle\Entity\Humour;

use Doctrine\ORM\EntityRepository;

/**
 * TripletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripletRepository extends EntityRepository
{
}
