carto_accueil_homepage:
    pattern:  /{_locale}
    defaults: { _controller: CartoAccueilBundle:Default:index, _locale:en }
    requirements:
        _locale: en|fr

carto_accueil_homepage_switch_language:
    pattern:  /switch_language/{lang}
    defaults: { _controller: CartoAccueilBundle:Default:switchLanguage }

carto_accueil_aboutus:
    pattern:  /{_locale}/aboutus
    defaults: { _controller: CartoAccueilBundle:Default:aboutus, _locale:en }
    requirements:
        _locale: en|fr

