carto_accueil_homepage:
    pattern:  /{_locale}
    defaults: { _controller: CartoAccueilBundle:Default:index, _locale: en }

carto_accueil_homepage_switch_language:
    pattern:  /switch_language/{lang}
    defaults: { _controller: CartoAccueilBundle:Default:switchLanguage }

carto_accueil_aboutus:
    pattern:  /aboutus
    defaults: { _controller: CartoAccueilBundle:Default:aboutus }

carto_accueil_contactus:
    pattern:  /contactus
    defaults: { _controller: CartoAccueilBundle:Default:contactus }
