parameters:
#    accueil.example.class: Carto\AccueiBundle\Example

services:
#    accueil.example:
#        class: %accueil.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
