parameters:
#    carto_accueil.example.class: Carto\AccueilBundle\Example

services:
#    carto_accueil.example:
#        class: %carto_accueil.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
